# Generated by Django 4.1.1 on 2023-07-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=32)),
                ('short_name', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(blank=True, choices=[('py', 'python'), ('js', 'javaScript'), ('cpp', 'c++')], max_length=30, null=True),
        ),
    ]
