# Generated by Django 4.1.1 on 2023-07-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_snippet_lang2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='lang',
        ),
    ]
