# Generated by Django 4.1.1 on 2023-07-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_snippet_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='shot_name',
            new_name='short_name',
        ),
    ]
