# Generated by Django 4.1.1 on 2023-07-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_rename_shot_name_language_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(blank=True, choices=[('py', 'python'), ('js', 'javaScript'), ('cpp', 'c++')], max_length=30, null=True),
        ),
    ]
